import Head from 'next/head';
import { GetServerSideProps, NextPage } from 'next';
import User from '../../models/User';
import { UserProfile } from '../../ts/types/user';
import UserProfileCard from '../../Components/Elements/UserProfileCard';

import { connect } from 'mongoose';
import * as jose from 'jose';

const MONGODB_URI = process.env.MONGODB_URI || '';
const JWT_SECRET = process.env.JWT_SECRET;

const Profile: NextPage<{  user: UserProfile}> = ({  user }) => {
 
  return (
    <>
      <Head>
        <title>cine.mize - profile</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <section className='flex flex-col gap-1'>
        <div className='bg-white dark:bg-dark fixed container left-1/2 -translate-x-2/4'>
          <UserProfileCard user={user} />
          <div className='pt-2 text-sm md:text-base flex justify-between sm:justify-start sm:gap-6'>
            <button>Posts</button>
            <button>{user?.followers?.length} seguidores</button>
            <button>{user?.following?.length} seguindo </button>
          </div>
        </div>
        
        <div className='pt-48 '>
            {Array.from(Array(200).keys()).map((item)=> {
              return <p key={item}>{item}</p>
            })}
            </div>
  
      </section>
    </>
  );
};
export default Profile;

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  await connect(MONGODB_URI).catch((err) => console.log(err));
  
  const jwt = ctx.req.cookies.CinemizeJWT;

  const response = await jose.jwtVerify(
    jwt!,
    new TextEncoder().encode(JWT_SECRET)
  );
  const _id = await response.payload.userId;
  const user = await User.findById(_id, {
    password: 0,
    createdAt: 0,
    _id: 0,
    email: 0,
    updatedAt: 0,
    __v: 0,
  });
  const userResponse = JSON.parse(JSON.stringify(user));

  

  return {
    props: {
      user: userResponse,
    },
  };
};
