import { NextPage } from 'next';
import Link from 'next/link';
import Head from 'next/head';

const NotFound: NextPage = () => {
  return (
    <>
      <Head>
        <title>cine.mize - 404</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex flex-col gap-2 text-center items-center pt-14'>
        <h3>Parece que esta página não existe.</h3>
        <Link href='/'>
          <a className='py-1 px-3 bg-indigo-600 rounded-md text-white text-sm'>
            Voltar
          </a>
        </Link>
      </div>
    </>
  );
};
export default NotFound;
