import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import ColorMode from '../Components/ColorMode/ColorMode';
import { Input, Form, Button } from './../Components/UI/Index';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>cine.mize</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex flex-col h-screen justify-center sm:flex-row sm:items-center sm:justify-end sm:gap-12 '>
        <h1 className='text-3xl text-center mb-12 sm:mb-0 sm:text-6xl sm:-mt-12 '>
          c<span className='text-indigo-600 dark:text-indigo-400'>i</span>ne
          <span className='text-indigo-600 dark:text-indigo-400'>.</span>mi
          <span className='text-indigo-600 dark:text-indigo-400'>z</span>e
        </h1>
        <div className='sm:w-6/12 md:w-80'>
          <h2 className='text-2xl text-center mb-6 '>join us today</h2>
          <Form className='gap-4 w-full'>
            <div>
              <Input
                type='text'
                className='rounded-md w-full dark:border-dark'
                placeHolder='Name'
              />
            </div>
            <div>
              <Input
                type='text'
                className='rounded-md w-full dark:border-dark'
                placeHolder='E-mail'
              />
            </div>
            <div>
              <Input
                type='password'
                className='rounded-md w-full dark:border-dark'
                placeHolder='Password'
              />
            </div>
            <Button className='bg-indigo-600 py-2 rounded-md'>
              Create Account
            </Button>
          </Form>
          <h3 className='text-center my-4'>Already have an account?</h3>
          <Link href='/'>
            <a className='block text-center text-md hover:text-gray-900 dark:hover:text-indigo-300 transition underline'>
              Sign in
            </a>
          </Link>
        </div>
      </div>
      <div className='fixed top-8 right-8 flex mt-auto mb-10 justify-left'>
        <ColorMode size={22} />
      </div>
    </>
  );
};

export default Home;
